export type BoardCategory = {
    name: string;
    boards: string[];
};

export const BOARD_CATEGORIES: BoardCategory[] = [
    {
        name: "Anime & Manga",
        boards: ["a", "c", "w", "m"],
    },
    {
        name: "Otaku Culture",
        boards: ["jp", "vt", "cgl", "mlp"],
    },
    {
        name: "Video Games",
        boards: ["v", "vg", "vp", "vr"],
    },
    {
        name: "Retro & Analog Gaming",
        boards: ["retro", "tg", "qst"],
    },
    {
        name: "Technology",
        boards: ["g", "sci"],
    },
    {
        name: "Visual Arts",
        boards: ["ic", "gd", "3", "p", "i", "wsg"],
    },
    {
        name: "Craft & DIY",
        boards: ["diy", "po", "ck"],
    },
    {
        name: "Screen & Sound",
        boards: ["tv", "mu", "co"],
    },
    {
        name: "Literature & History",
        boards: ["lit", "his"],
    },
    {
        name: "Lifestyle",
        boards: ["fa", "fit", "adv", "lgbt"],
    },
    {
        name: "Transport & Travel",
        boards: ["o", "trv", "out"],
    },
    {
        name: "Sports",
        boards: ["sp", "asp"],
    },
    {
        name: "Business & Politics",
        boards: ["biz", "pol", "news", "int"],
    },
    {
        name: "Random & Misc",
        boards: ["b", "r9k", "x", "soc", "s4s", "bant"],
    },
    {
        name: "Hentai (2D)",
        boards: ["h", "e", "u", "d", "y", "aco"],
    },
    {
        name: "Adult (3D)",
        boards: ["s", "hc", "hm", "hr", "gif", "r"],
    },
];

export const BOARD_NAMES: Record<string, string> = {
    a: "Anime & Manga",
    c: "Anime/Cute",
    w: "Anime/Wallpapers",
    m: "Mecha",
    cgl: "Cosplay & EGL",
    jp: "Otaku Culture",
    vt: "Virtual YouTubers",
    v: "Video Games",
    vg: "Video Game Generals",
    vp: "Pokémon",
    vr: "Retro Games",
    q: "Quests",
    retro: "Retro Games",
    co: "Comics & Cartoons",
    g: "Technology",
    tv: "Television & Film",
    k: "Weapons",
    o: "Auto",
    an: "Animals & Nature",
    tg: "Traditional Games",
    sp: "Sports",
    asp: "Alternative Sports",
    sci: "Science & Math",
    his: "History & Humanities",
    int: "International",
    out: "Outdoors",
    toy: "Toys",
    i: "Oekaki",
    po: "Papercraft & Origami",
    p: "Photography",
    ck: "Food & Cooking",
    ic: "Artwork/Critique",
    wg: "Wallpapers/General",
    lit: "Literature",
    mu: "Music",
    fa: "Fashion",
    3: "3DCG",
    gd: "Graphic Design",
    diy: "Do-It-Yourself",
    wsg: "Worksafe GIF",
    qst: "Quests",
    biz: "Business & Finance",
    trv: "Travel",
    fit: "Fitness",
    x: "Paranormal",
    adv: "Advice",
    lgbt: "LGBT",
    mlp: "Pony",
    news: "Current News",
    wsr: "Worksafe Requests",
    vip: "Very Important Posts",
    b: "Random",
    r9k: "ROBOT9001",
    pol: "Politically Incorrect",
    bant: "International/Random",
    soc: "Cams & Meetups",
    s4s: "Shit 4chan Says",
    s: "Sexy Beautiful Women",
    hc: "Hardcore",
    hm: "Handsome Men",
    h: "Hentai",
    e: "Ecchi",
    u: "Yuri",
    d: "Hentai/Alternative",
    y: "Yaoi",
    t: "Torrents",
    hr: "High Resolution",
    gif: "Adult GIF",
    aco: "Adult Cartoons",
    r: "Adult Requests",
};
